In [1]:
import numpy as np

1) For a given numpy array, how will you change the dimensions to 5 using the existing parameters in the numpy array.
my_array = numpy.array([[[[1,3,4]]]])

A. numpy.array(my_array, ndim= my_array.ndmin + 1)

B. numpy.array(my_array, ndmin=5)

C. numpy.array(my_array, ndim=5)

D. numpy.array(my_array, ndim=1)

In [8]:
my_array = np.array([[[[1,3,4]]]])
my_array1= np.array(my_array, ndmin=5)
my_array1.ndim

5

2) For the given numpy arrays, Array1 and Array2, what will be the dot product for the same.
Array1 = array([[1, 2, 3], [4, 5, 6]])
Array2 = array([[2, 3],[3, 2]])

A. None of the Above
B. array([[ -9, 6, -1],[-12, 18, -7]])
C. Valueerror
D. Keyerror

In [10]:
Array1 =np.array([[1, 2, 3], [4, 5, 6]])
Array2 = np.array([[2, 3],[3, 2]])
np.dot(Array1, Array2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

3) In a given numpy array, using the slicing operations print the reverse of the array.

array = np.array([10,3,1,203,404,204,20,302,30,402,192])

A. array1[len(array1):0]

B. array[::-1]

C. array1[-1:-len(array1)]

D. array[-1:0]

In [11]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])
print(array[::-1])

[192 402  30 302  20 204 404 203   1   3  10]


4) What is the output of the below code:

 a = [[1, 0], [0, 1]]  b = [[4, 1], [2, 2]]  np.dot(a, b)

A. None of the above

B. array([[1, 1], [2, 2]])

C. array([[4, 4],[2, 4]])

D. array([[4, 1],[2, 2]])


In [12]:
 a = [[1, 0], [0, 1]]
 b = [[4, 1], [2, 2]]
 np.dot(a, b)

array([[4, 1],
       [2, 2]])

5) What is the output of the following code:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

A.499128

B.909128

C.399118

D.Value Error


In [13]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

499128

6) What will be output for the following code?
import numpy as np
a = np.array([3, 7, 32], dtype = complex)
print(a)

A. [ 3.0+0.j 7.0+0.j 32.0+0.j]

B. [ 3.+0.j 7.+0.j 32.+0.j]

C. Error

D. [ 3.+0.k 7.+0.j 32.+0.l]

In [14]:
import numpy as np
a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [ ]:
# prompt: explain dtype = complex

import numpy as np
# The dtype = complex parameter in the NumPy array() function
# specifies that the data type of the array elements should be complex numbers.
# Complex numbers are numbers that have both a real and an imaginary component.
# They are written in the form a + bj, where a is the real component, b is the imaginary component, and j is the imaginary unit (√-1).

# When you create a NumPy array with dtype = complex, each element in the array will be a complex number.
# For example, the following code creates a NumPy array with three complex numbers:

a = np.array([3, 7, 32], dtype = complex)
print(a)

# This will print the following output:

# [ 3. +0.j  7. +0.j 32. +0.j]

# Each element in the array is a complex number with a real component and an imaginary component.
# The real component is the number before the + sign, and the imaginary component is the number after the + sign.
# The j indicates that the imaginary component is the square root of -1.


7) How to replace all values greater than a given value with a given cutoff? For example: In array ‘a’, replace all values greater than 30 to 30 and less than 10 to 10.
Input: np.random.seed(100) a = np.random.uniform(1,50, 20)

A.Both of the above

B.np.clip(a, a_min=10, a_max=30)

C.np.where(a < 10, 10, np.where(a > 30, 30, a))

D.None of the above


In [19]:
 np.random.seed(100)
 a = np.random.uniform(1,50, 20)
 print(a)
 b=np.where(a < 10, 10, np.where(a > 30, 30, a))
 print(b)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


8) For the given arrays, array1 and array2, if we stack the two arrays row wise, what will be the output?

array1 = np.array([[1,2],[3,4]])

array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

A.array([[ 1, 2, 3, 4],[ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 9, 10]])

B.None of the above

C.array([[ 1, 2, 3, 4, 1], [2, 3, 4, 5, 6],[ 7, 8, 9, 10]])

D.array([[ 1, 2],[ 3, 4],[ 1, 2],[ 3, 4],[ 5, 6],[ 7, 8],[ 9, 10]])


In [21]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(array1)
print(array2 )

[[1 2]
 [3 4]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


9) For a given numpy array, how are you going to insert a new value at the specified position?

array = np.array([10,3,1,203,404,204,20,302,30,402,192])  

Elem_to_be_inserted = [1,2,3,4]  

The position to be inserted at = before 404


A.numpy.insert(array2, 404, array2)

B.numpy.insert(array1, np.where(404), array2)


**C.numpy.insert(array1, 4, array2)**

D.numpy.insert(array2, np.index(404), array2)

In [38]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])

Elem_to_be_inserted = [1,2,3,4]
print(array)
print(Elem_to_be_inserted)
index = np.where(array == 404)[0][0]
print(index)
array1=np.insert(array,  index, Elem_to_be_inserted)
print(array1)

[ 10   3   1 203 404 204  20 302  30 402 192]
[1, 2, 3, 4]
4
[ 10   3   1 203   1   2   3   4 404 204  20 302  30 402 192]


10) Create a 3x3 matrix using numpy, and all the values of the matrix must be a constant k.


A. numpy.random.random((3,3), ‘k’)

**B. numpy.full((3,3), ‘k’)**

C. numpy.eye(‘k’)

D. numpy.ones(3,3)

In [43]:
np.full((3,3), 'K')

array([['K', 'K', 'K'],
       ['K', 'K', 'K'],
       ['K', 'K', 'K']], dtype='<U1')

11) For the given python code that implements bubble sort, what will be the output for the given numpy array.

 def bub_sort(array):

 for i in range(0, len(array)):

  for j in range(0, len(array) - i - 1):

    if array[j] < array[j + 1]:

      temp = array[j]

      array[j] = array[j + 1]

      array[j+1] = temp

    return array

my_array = numpy.array([20,14,25,16,45,60,12,9])



**A. array([ 9, 12, 14, 16, 20, 25, 45, 60])**

B.array([60, 45, 20, 25, 16, 14, 12, 9])

C.array([60, 45, 25, 20, 16, 14, 12, 9])

D.array([ 9, 12, 16, 14, 20, 25, 45, 60])


In [52]:
def bub_sort(array):
 for i in range(0, len(array)):
  for j in range(0, len(array) - i - 1):
    if array[j] < array[j + 1]:
      temp = array[j]
      array[j] = array[j + 1]
      array[j+1] = temp
    return array
my_array = np.array([20,14,25,16,45,60,12,9])
bub_sort(my_array)

array([20, 14, 25, 16, 45, 60, 12,  9])

In [53]:
# prompt: what is bubble sort

# Bubble Sort is a simple sorting algorithm that repeatedly steps through a list,
# compares adjacent elements and swaps them if they are in the wrong order.
# The pass through the list is repeated until the list is sorted.

import numpy as np
def bubble_sort(list_):
  n = len(list_)
  for i in range(n):
    swapped = False
    for j in range(0, n-i-1):
      if list_[j] > list_[j+1]:
        list_[j], list_[j+1] = list_[j+1], list_[j]
        swapped = True
    if swapped == False:
      break
  return list_

my_array = np.array([20,14,25,16,45,60,12,9])
bubble_sort(my_array)

array([20, 14, 25, 16, 45, 60, 12,  9])

12) For a given numpy array of the shape (2,5) ,How will you reshape the array in the shape (5,2).

A.numpy.arange(5,2)

**B.numpy.reshape(5,2)**

C.numpy.shape(5,2)

D.numpy.reshape((2,5) == (5,2))


In [56]:
array=np.full((2,5), 1)
print(array)
array1=np.reshape(array, (5,2))
print(array1)

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


13) What will be the shape of the sample numpy array after flattening it?

Sample = numpy.array([[1,2],[3,4],[5,6],[7,8]])

A.array([1, 2], [3, 4], [5, 6], [7, 8])

**B.array([1, 2, 3, 4, 5, 6, 7, 8])**

C.None of the above

D.array([1], [2], [3], [4], [5], [6], [7], [8])

In [59]:
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])
print(Sample)
print(Sample.flatten())

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


14) In the given array, how can we get the following
output = array([2, 5, 8]).
Sample = numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

A.array[0:3][1]

**B.array[0:3, 1]**

C.array[[0:3], [1]]

D.None of the above

In [61]:
Sample = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(Sample)
print(Sample[0:3, 1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[2 5 8]


15) Given two numpy arrays, we will perform Horizontally stack the given arrays array1 and array2. What will be the output of the above operation? The sample arrays are as follows.

Array1 = numpy.arange(20,2)

Array2 = numpy.array([1,2,3,4,5,6,7,8,9,10])


A. array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

**B.None of the above**

C.array([[ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

D.array([[ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [66]:
Array1 = np.arange(20,2)
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])
print('Array1')
print(Array1)
print('Array2')
print(Array2)
print('Array hstack')
print(np.hstack((Array1, Array2)))


Array1
[]
Array2
[ 1  2  3  4  5  6  7  8  9 10]
Array hstack
[ 1  2  3  4  5  6  7  8  9 10]


16) For the given arrays, array1 and array2, if we stack the two arrays column wise, what will be the output?

array1 = np.array([[1,2],[3,4]])

array2 = np.array([[5,6],[7,8]])

A.array([[1, 2, 5, 6 ,3, 4, 7, 8]])

**B.array([[1, 2, 5, 6],[3, 4, 7, 8]])**

C.None of the above

D.array([[1, 2], [5, 6],[3, 4], [7, 8]])

In [68]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
print(array1)
print(array2)
print(np.column_stack((array1, array2)))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


17) Given two vectors A and B, find the cross product between the two vectors.

A = numpy.array([[4],[12],[29]])

B = numpy.array([[13],[21],[4]])

A.array([[-560 360 -71]])

B.array([[-561 361 -72]])

C.array([[-561 360 -72]])

D.array([[-555 361 -72]])

In [85]:
A = np.array([[4],[12],[29]])
B = np.array([[13],[21],[4]])
print(A)
print(B)
print(np.cross(A, B))
#

[[ 4]
 [12]
 [29]]
[[13]
 [21]
 [ 4]]


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

18) Given two vectors A and B, find the correlation coefficient of the following vectors.

A = numpy.array([1,3,5,7,9,11,13,15,17,19,21,23,25])

B = numpy.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])

A.array([[1., 1.],[0., 1.]])

B.array([[0., 1.],[1., 1.]])

**C.array([[1., 1.],[1., 1.]])**

D.array([[1., 0.],[1., 1.]])

In [88]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
print(A)
print(B)
print(np.corrcoef(A, B))
#

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]
[[1. 1.]
 [1. 1.]]


19) Create a nested numpy array from a given dictionary data.

sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}

A.array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 10, 5])]], dtype=object)

**B.array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)**

C.array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [1, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)

D.array([[1, list([1, 1])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)

In [89]:
sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}
print(sample)
print(np.array(sample))

{1: [1, 2], 2: [[1], [2]], 3: [[1, 2], [3, 4], [4, 5]], 4: [1], 5: [1, 2, 3, 4, 5]}
{1: [1, 2], 2: [[1], [2]], 3: [[1, 2], [3, 4], [4, 5]], 4: [1], 5: [1, 2, 3, 4, 5]}


20) A 2-dimensional array with 3 rows and 3 columns containing random numbers from 1 to 9 is given as -
arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])

Find the difference between the maximum element across the columns and the minimum element across the rows.

A.[7 1 2]

B.[7 3 2]

C.[8 3 2]

D.[7 3 1]

In [96]:
arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])

max_element_cols = np.max(arr1, axis=0)  # Maximum element across columns
min_element_rows = np.min(arr1, axis=1)  # Minimum element across rows
print(arr1)
difference = max_element_cols - min_element_rows
print(max_element_cols)
print(min_element_rows  )
print(difference)  # Output: [7 3 2]

[[3 2 1]
 [6 4 5]
 [8 7 9]]
[8 7 9]
[1 4 7]
[7 3 2]


21) The command to find the number of elements in the following array “N” is
N=np.array([ 99 , None , 49 , Nan, str , np.nan ,63 , 50 ,( ) ,[ ] ,{ }, ....]).


**A.len(N)**

B.N.count()

**C.np.size(N)**

D.N.size()

In [107]:
N=np.array([ 99 , None , 49 , np.nan, str , np.nan ,63 , 50 ])
print(len(N))
print(np.size(N))


8
8


22) The output of the code given below is:

List =[3,9,12,15]

a=(x**3 for x in list)

print(next(a))


A.81

B.27

C.9

D.12

In [109]:
List =[3,9,12,15]
a=(x**3 for x in List)
print(next(a))


27


23) Create a sequence number from 13 to 22 and increment by 4 .What is the index element 17?
0
3
2
1

In [111]:
import numpy as np

sequence = np.arange(13, 23, 4)
print(sequence)
index_17 = np.where(sequence == 17)[0][0]
print(index_17)


[13 17 21]
1


24) Consider a variable job=”analyst”.Which of the following expression(s) will retrieve the last from the string?
job[7]
JOB[LEN(JOB)-1]
job[5:6]
JOB[-1]

In [119]:
JOB=['A','N','A','L','Y','S','T']
print(JOB[-1])

T


25) Given a NumPy array ,

arr=np.array( [ [6,9,12] , [8,3,7] , [9,8,0] ] )

Find the correct command from the following options to get an output array as [27 18 17]?

A.np.sum(arr,axis=1)

B.np.sum(arr,axis=0)

C.None of the options are correct

D.np.sum(arr)

In [122]:
arr=np.array( [ [6,9,12] , [8,3,7] , [9,8,0] ] )
print(arr)
print(np.sum(arr,axis=1))


[[ 6  9 12]
 [ 8  3  7]
 [ 9  8  0]]
[23 20 19]
